[project]
name = "refund-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "fastapi[standard]>=0.116.1",
  "pytest>=8.4.1",
  "python-dotenv>=1.1.1",
  "requests>=2.32.4",
  "sqlalchemy>=2.0.42",
]

[tool.ruff]
ignore = ["E402"]
